---
title: "Professional Experience"
---

# Professional Experience

### Indiana University Health  
**Senior Data Scientist Analyst**  
*February 2021 – Present*  
- Driving data-driven decision-making in healthcare by developing patient cohorts and implementing advanced data analysis techniques.  
- Collaborated with students on capstone projects and automated cohort development using Azure Data Warehouse and R.  

### Lucid Services Group  
**Data Analyst**  
*July 2019 – Present*  
- Streamlined cohort development for healthcare research, leveraging R and Azure Data Warehouse.  
- Mentored students and professionals in healthcare analytics.

### Past Roles  
- **Instructor** at Sollers College and USA English Audiovisual School, teaching data science and English courses.  
- **Real-World Data Analyst** at Kelly Services, improving cohort extraction workflows using SAS, R, and YAML documentation.  
- **Data Analyst** and **Statistician** in various industries, focusing on statistical modeling, cohort development, and analytics workflows.

---