---
title: 'Git hub and Azure Repository: Person Access Tokens (PAT)'
author: Harlan A Nelson
date: '2020-12-26'
slug: github-and-azure-repos-person-access-tokens-pat
categories:
  - security
  - authentication
tags: [PAT, authentication]
---

*Git Hub* and *Azure Ropository* are moving away from passwords to other means of authentication.  There are a few ways to authenticate:

   * Personal Access Tokens (PAT).
   * Token keys
   * Two step identification.
   * Use of PATs as passwords entered when authentication is needed.
   
  The PATs are used in applications that access accounts such as your repositories.  The PAT is stored securely in the app and then used for authentication. 
  If you are using the command line, then token keys or two step identification might be better.  The PATs can be entered at the time authentication is needed, but
  you have to know the PAT, that does not seem like their intended use.
  
  There are a couple help pages to learn about *Personal Access Tokens*
  
  * [github: Creating Personal Access Tokens](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)
  * [Azure Devops: Use Personal Access Tokens](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
